### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Fess23** [sneak-it/Normalized-Run-Speed#4]
Sm 1.11
mm 1.11
Max speed with awp is 196 unit per second.

**Comment by sneak-it** [comment]
Going to need more information here.

Did you extract plugin file and gamedata to the proper folders?

What game?

Error logs?

And lastly, post output of `sm plugins list`

**Comment by Fess23** [comment]
1. Yes 
2. Counter strike: global offensive
3. `  01 "[VIP] DeathEvents (discord: Drimer#6995)" (1.0) by Dirmer
  02 "[VIP] Weapons & Knives" (1.7.7.1) by kgns | oyunhost.net & Romeo
  03 "[PENIS]" (1.0) by Drimer
  04 "[VIP] CHAT (scp)" (3.3) by R1KO
  05 "[VIP] Special Skins(Agents)" (2.1) by SniffRx
  06 "[VIP] AWP Manager" (v1.0.1) by Delfram
  07 "[VIP] Core" (3.0.3 R) by R1KO
  08 "Basic Comm Control" (0.8.6-4dc206d) by AlliedModders LLC
  09 "Material Admin" (0.8.6-4dc206d) by Material Admin Dev Team
  10 "Basic Votes" (1.11.0.6916) by AlliedModders LLC
  11 "Material Admin Checker" (0.8.6-4dc206d) by psychonic, Ca$h Munny, Sarabveer(VEER), Bloomstorm
  12 "Admin Menu" (0.8.6-4dc206d) by AlliedModders LLC
  13 "RoundEnd Super Advertisement" (1.3) by GARAYEV
  14 "Chat Wheel Blocker" (1.1) by MINFAS, Sples1
  15 "ViewAngle Fix" (0.2) by Alvy Piper / sapphyrus / dylan
  16 "Sound Commands" (1.11.0.6906) by AlliedModders LLC
  17 "[CS:GO] ResetScore" (1.1) by pracc
  18 "Weapon Restrict [FORK]" (3.1.9 F) by Someone & Dr!fter
  19 "Particle Snow 2020" (1.2.0 (rewritten by Grey83)) by FLASHER
  20 "[ANY] Directory Downloader" (1.4.1) by inklesspen
  21 "Реклама" (1.4.1) by Pheonix (‰7Феникс7‰)
  22 "Simple Chat Processor (Redux)" (1.1.5) by Simple Plugins, Mini
  23 "Quake Sounds v3" (3.5.1) by Spartan_C001
  24 "Fix Hint Color Messages" (1.1.0) by Phoenix (‰7Феникс7‰)
  25 "[Levels Ranks] Core" (v3.1.2) by RoadSide Romeo & Wend4r
  26 "[LR] Module - FakeRank" (v3.1) by RoadSide Romeo & Wend4r
  27 "Admin File Reader" (1.11.0.6906) by AlliedModders LLC
  28 "Fun Votes" (1.11.0.6906) by AlliedModders LLC
  29 "Anti-Flood" (1.11.0.6906) by AlliedModders LLC
  30 "Reserved Slots" (1.11.0.6906) by AlliedModders LLC
  31 "Basic Chat" (1.11.0.6906) by AlliedModders LLC
  32 "Basic Info Triggers" (1.11.0.6906) by AlliedModders LLC
  33 "Player Commands" (1.11.0.6906) by AlliedModders LLC
  34 "Basic Commands" (1.11.0.6906) by AlliedModders LLC
  35 "Client Preferences" (1.11.0.6906) by AlliedModders LLC
  36 "Basic Votes" (1.11.0.6906) by AlliedModders LLC
  37 "Fun Commands" (1.11.0.6906) by AlliedModders LLC
  38 "Normalized Run Speed" (0.6) by sneaK
  39 "PushFix - Definitive Edition" (1.0.0) by Original idea xutaxkamay | Implementation GAMMACASE
  40 "crouchboostfix" (2.0.2) by https://github.com/t5mat
  41 "HeadBugFix" (1.0.0) by GAMMA CASE
  42 "RNGFix" (1.1.2) by rio
  43 "Momentum surf fix '2" (1.1.5) by GAMMA CASE
  44 "Speedometer" (1.0) by 88
  45 <Failed> "Nextmap" (1.11.0.6906) by AlliedModders LLC`

**Comment by sneak-it** [comment]
No error logs?

Edit: What are you using to verify the speed? `cl_showpos 1` will not return an accurate number.

Edit 2: 196 u/s isn't even correct vanilla CS:GO behavior, AWP run speed is 200 u/s. You've got something weird going on here.
